/* runtime flag helper autogenerated 2025‑06‑22 */
export const FEATURE_FLAGS = {
  INTELLIGENCE_V2_ENABLED:        process.env.FEATURE_INTELLIGENCE_V2 !== 'false',
  VECTOR_SEARCH_ENABLED:          process.env.FEATURE_VECTOR_SEARCH   !== 'false',
  RECURSIVE_REASONING_ENABLED:    process.env.FEATURE_RECURSIVE_REASONING !== 'false',
  RELATIONSHIP_MAPPING_ENABLED:   process.env.FEATURE_RELATIONSHIP_MAPPING !== 'false',
  PROACTIVE_DELIVERY_ENABLED:     process.env.FEATURE_PROACTIVE_DELIVERY   !== 'false',
  ENHANCED_COLLECTIONS_ENABLED:   process.env.FEATURE_ENHANCED_COLLECTIONS !== 'false',
  ADVANCED_NOTIFICATIONS_ENABLED: process.env.FEATURE_ADVANCED_NOTIFICATIONS !== 'false',
} as const;
/* ---- V3 PHASED ROLLOUT: STEP‑1 ----------------------------------- */
export const V3_STEP_1_ENABLED = process.env.V3_STEP_1_ENABLED === 'true';
