export function normalizeNote(row: any) {
  return {
    id: row.id,
    content: row.content ?? '',
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    todos: row.todos ?? [],
    miraResponse: row.mira_response,
    aiGeneratedTitle: row.ai_generated_title,
    tokenUsage: row.token_usage,
    isProcessing: row.is_processing,
    aiContext: row.ai_context,
    aiSuggestion: row.ai_suggestion,
    richContext: row.rich_context,
    collection: row.collection,
    collectionId: row.collection_id,
    userId: row.user_id,
    mode: row.mode,
    audioUrl: row.audio_url,
    mediaUrl: row.media_url,
    transcription: row.transcription,
    imageData: row.image_data,
    vectorDense: row.vector_dense,
    vectorSparse: row.vector_sparse,
    intentVector: row.intent_vector,
    version: row.version,
    originalContent: row.original_content,
    lastUserEdit: row.last_user_edit,
    protectedContent: row.protected_content,
    processingPath: row.processing_path,
    classificationScores: row.classification_scores,
    isShared: row.is_shared,
    shareId: row.share_id,
    privacyLevel: row.privacy_level,
  };
}